
var PROJECTIONPROPERTIES = [{title:"Prj4 String",value:"",id:"proj4",enabled:"1",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:""}];

var MAPPROPERTIES = [{title:"Name*",id:"name",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",maxchars:"10",required:"true"},tooltip:"Prefix attached to map, scalebar and legend GIF filenames created using this mapfile. It should be kept short."},
{title:"Size",id:"size",enabled:"0",type:"label"},{title:"X",id:"$SIZE&x",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*$",required:"true"},tooltip:"Size in pixels of the output image (i.e. the map)."},
{title:"Y",id:"$SIZE&y",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*$",required:"true"},tooltip:"Size in pixels of the output image (i.e. the map)."},
{title:"Extent",id:"extent",enabled:"0",type:"label"},
{title:"Minx", id:"$EXTENT&minx",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the map to be created."},
{title:"Miny",id:"$EXTENT&miny",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the map to be created."},
{title:"Maxx",id:"$EXTENT&maxx",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the map to be created."},
{title:"Maxy",id:"$EXTENT&maxy",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the map to be created."},
{title:"Status",id:"status",enabled:"0",type:"switch"},
{title:"Shapepath",id:"shapepath",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Path to the directory holding the shapefiles or tiles. There can be further subdirectories under SHAPEPATH."},
{title:"Symbolset",id:"symbolset",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Filename of the symbolset to use. Can be a path relative to the mapfile, or a full path."},
{title:"FontSet",id:"fontset",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Filename of fontset file to use. Can be a path relative to the mapfile, or a full path."},
{title:"Imagetype",id:"imagetype",enabled:"0",type:"dropdown",doptions:"jpeg|pdf|png|svg|userdefined"},
{title:"ImageColor",id:"imagecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to initialize the map with (i.e. background color). "},
{title:"Imagequality",id:"imagequality",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:""},
{title:"Resolution",id:"resolution",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Sets the pixels per inch for output, only affects scale computations."},
{title:"Defresolution",id:"defresolution",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Sets the reference resolution (pixels per inch) used for symbology."},
{title:"Scaledenom",id:"scaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Computed scale of the map. Set most often by the application."},
{title:"MaxSize",id:"maxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Sets the maximum size of the map image. This will override the default value."},
{title:"Transparent",id:"transparent",enabled:"0",type:"switch"},
{title:"Units",id:"units",enabled:"0",type:"dropdown",doptions:"dd|feet|inches|kilometers|meters|miles|nauticalmiles"},
{title:"TemplatePattern",id:"templatepattern",enabled:"0",type:"textbox",vstring:{required:"true"},tooltip:"This defines a regular expression to be applied to requests to change the TEMPLATE parameters via URL requests"},
{title:"DataPattern",id:"datapattern",enabled:"0",type:"textbox",vstring:{required:"true"},tooltip:"This defines a regular expression to be applied to requests to change DATA parameters via URL requests"},
{title:"Debug",id:"debug",enabled:"0",type:"dropdown",doptions:"on|off|0|1|2|3|4|5"}, {title:"Interlace",id:"interlace",enabled:"0",type:"switch"},
{title:"Angle",id:"angle",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true",maxval:"360"},tooltip:"Angle, given in degrees, to rotate the map. The rendered map will rotate in a clockwise direction. "},
{title:"Config",id:"config",enabled:"0",type:"label"},
{title:"CGI_CONTEXT_URL",id:"CONFIG^cgi_context_url",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s_]+$",required:"true"},tooltip:"This CONFIG parameter can be used to enable loading a map context from a URL. "},
{title:"MS_ENCRYPTION_KEY",id:"CONFIG^ms_encryption_key",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s_]+$",required:"true"},tooltip:"This CONFIG parameter can be used to specify an encryption key that is used with MapServer’s msencypt utility."},
{title:"MS_ERRORFILE",id:"CONFIG^ms_errorfile",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s_]+$",required:"true"},tooltip:"This CONFIG parameter can be used to write MapServer errors to a file."},
{title:"MS_NONSQUARE",id:"CONFIG^ms_nonsquare",enabled:"0",type:"switch"},
{title:"ON_MISSING_DATA",id:"CONFIG^on_missing_data",enabled:"0",type:"dropdown",doptions:"FAIL|LOG|IGNORE"},
{title:"PROJ_LIB",id:"CONFIG^proj_lib",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"This CONFIG parameter can be used to define the location of your EPSG files for the Proj.4 library."}];


 var LAYERPROPERTIES = [{title:"Name",id:"name",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Short name for this layer. This name is the link between the mapfile and web interfaces that refer to this name. They must be identical. The name should be unique, unless one layer replaces another at different scales. Use the GROUP option to associate layers with each other. It is recommended that the name not contain spaces, special characters, or begin with a number"},
{title:"Type",id:"type",enabled:"0",type:"dropdown",doptions:"chart|circle|line|point|polygon|raster|query"},
{title:"Group",id:"group",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Name of a group that this layer belongs to. The group name can then be reference as a regular layer name in the template files, allowing to do things like turning on and off a group of layers at once."},
{title:"Status",id:"status",enabled:"0",type:"radio",doptions:"on|off|default"},
{title:"ConnectionType",id:"connectiontype",enabled:"0",type:"dropdown",doptions:"contour|kerneldensity|local|ogr|oraclespatial|plugin|postgis|sde|union|uvraster|wfs|wms"},
{title:"Connection",id:"connection",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Database connection string to retrieve remote data."},
{title:"Plugin",id:"plugin",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Additional library to load by MapServer, for this layer. "},
{title:"Data",id:"data",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Full filename of the spatial data to process. No file extension is necessary for shapefiles."},
{title:"FilterItem",id:"filteritem",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Item to use with simple FILTER expressions. OGR and shapefiles only."},
{title:"Filter",id:"filter",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"This parameter allows for data specific attribute filtering that is done at the same time spatial filtering is done, but before any CLASS expressions are evaluated. The string is simply a mapserver regular expression"},
{title:"Geomtransform",id:"geomtransform",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Used to indicate that the current feature will be transformed."},
{title:"StyleItem",id:"styleitem",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Styling based on attributes or generated with Javascript"},
{title:"TileIndex",id:"tileindex",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Name of the tileindex file or layer. A tileindex is similar to an ArcInfo library index. The tileindex contains polygon features for each tile. The item that contains the location of the tiled data is given using the TILEITEM parameter."},
{title:"TileItem",id:"tileitem",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Item that contains the location of an individual tile, default is “location”."},
{title:"TileSrs",id:"tilesrs",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Name of the attribute that contains the SRS of an individual tile."},
{title:"MaxScaleDenom",id:"maxscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum scale at which this LAYER is drawn. Scale is given as the denominator of the actual scale fraction, for example for a map at a scale of 1:24,000 use 24000."},
{title:"MinScaleDenom",id:"minscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum scale at which this LAYER is drawn. Scale is given as the denominator of the actual scale fraction, for example for a map at a scale of 1:24,000 use 24000."},
{title:"Extent",id:"extent",enabled:"0",type:"label"},
{title:"Minx",id:"$EXTENT&minx",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the data. "},
{title:"Miny",id:"$EXTENT&miny",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the data. "},
{title:"Maxx",id:"$EXTENT&maxx",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the data. "},
{title:"Maxy",id:"$EXTENT&maxy",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the data. "},
{title:"Classitem",id:"classitem",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Item name in attribute table to use for class lookups."},
{title:"LabelItem",id:"labelitem",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Item name in attribute table to use for class annotation (i.e. labeling)."},
{title:"Classgroup",id:"classgroup",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Specify the class’s group that would be considered at rendering time. The CLASS object’s GROUP parameter must be used in combination with CLASSGROUP."},
{title:"Mask",id:"mask",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"The data from the current layer will only be rendered where it intersects features from the [layername] layer. [layername] must reference the NAME of another LAYER defined in the current mapfile. can be any kind of mapserver layer, i.e. vector or raster. "},
{title:"MaxFeautres",id:"maxfeatures",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Specifies the number of features that should be drawn for this layer in the CURRENT window. Has some interesting uses with annotation and with sorted data (i.e. lakes by area)."},
{title:"MaxGeoWidth",id:"maxgeowidth",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum width, in the map’s geographic units, at which this LAYER is drawn. If MAXSCALEDENOM is also specified then MAXSCALEDENOM will be used instead."},
{title:"MinGeoWidth",id:"mingeowidth",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum width, in the map’s geographic units, at which this LAYER is drawn. If MINSCALEDENOM is also specified then MINSCALEDENOM will be used instead."},
{title:"Offsite",id:"offsite",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Sets the color index to treat as transparent for raster layers."},
{title:"LabelCache",id:"labelcache",enabled:"0",type:"switch"},
{title:"PostLabelCache",id:"postlabelcache",enabled:"0",type:"radio",doptions:"True|False"},
{title:"LabelMaxScaleDenom",id:"labelmaxscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum scale at which this LAYER is labeled."},
{title:"LabelMinScaleDenom",id:"labelminscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum scale at which this LAYER is labeled."},
{title:"LabelRequires",id:"labelrequires",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"The expression consists of a boolean expression based on the status of other layers, each [layer name] substring is replaced by a 0 or a 1 depending on that layer’s STATUS and then evaluated as normal. Logical operators AND and OR can be used."},
{title:"Tolerance",id:"tolerance",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Sensitivity for point based queries."},
{title:"ToleranceUnits",id:"toleranceunits",enabled:"0",type:"dropdown",doptions:"pixels|feet|inches|kilometers|meters|miles|nauticalmiles|dd"},
{title:"Template",id:"template",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Used as a global alternative to CLASS TEMPLATE."},
{title:"Header",id:"*header",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use before a layer’s set of results have been sent. Multiresult query modes only."},
{title:"Footer",id:"footer",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use after a layer’s set of results have been sent. Multiresult query modes only."},
{title:"Requires",id:"requires",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Sets context for displaying this layer"},
{title:"SizeUnits",id:"sizeunits",enabled:"0",type:"dropdown",doptions:"feet|inches|kilometers|meters|miles|nauticalmiles|pixels"},
{title:"SymbolScaleDenom",id:"symbolscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The scale at which symbols and/or text appear full size. This allows for dynamic scaling of objects based on the scale of the map. If not set then this layer will always appear at the same size"},
{title:"Debug",id:"debug",enabled:"0",type:"dropdown",doptions:"on|off|0|1|2|3|4|5"},
{title:"Dump",id:"dump",enabled:"0",type:"radio",doptions:"True|False"},
{title:"Encoding",id:"encoding",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"The encoding used for text in the layer data source. The value must be supported by ICONV"},
{title:"Transparency",id:"transparency",enabled:"0",type:"radio",doptions:"True|False"},
{title:"Opacity",id:"opacity",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:""},
{title:"Transform",id:"transform",enabled:"0",type:"textbox","doptions":"ul|uc|ur|lc|cc|lr|ll|lc|lr"},
{title:"Units",id:"units",enabled:"0",type:"dropdown",doptions:"dd|feet|inches|kilometers|meters|miles|nauticalmiles|percentages|pixels"},
{title:"UTFData",id:"utfdata",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"A UTFGrid JSON template. MapServer expression syntax (expressionObj). If no UTFDATA is provided, no data beyond the UTFITEM values will be exposed. If UTFITEM is set, the UTFDATA expose those so that keys and data can be connected. "},
{title:"UTFItem",id:"utfitem",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"The attribute to use as the ID for the UTFGrid. If a UTFITEM is not set, the sequential id (based on rendering order) is being used. If UTFITEM is set, the UTFDATA expose those so that keys and data can be connected. "},
{title:"Processing",id:"processing",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Passes a processing directive to be used with this layer. The supported processing directives vary by layer type, and the underlying driver that processes them."}];

var WEBPROPERTIES = [{title:"MinScaleDenom",id:"minscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum scale at which this interface is valid."},
{title:"MaxScaleDenom",id:"maxscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum scale at which this interface is valid. "},
{title:"ImagePath",id:"imagepath",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Path to the temporary directory for writing temporary files and images. Must be writable by the user the web server is running as. Must end with a / or depending on your platform."},
{title:"ImageUrl",id:"imageurl",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Base URL for IMAGEPATH. This is the URL that will take the web browser to IMAGEPATH to get the images."},
{title:"BrowseFormat",id:"browseformat",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Format of the interface output, using MapServer CGI."},
{title:"LegendFormat",id:"legendformat",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"\/\+]*$",required:"true"},tooltip:"Format of the legend output, using MapServer CGI. "},
{title:"QueryFormat",id:"queryformat",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"\/\+]*$",required:"true"},tooltip:"Format of the query output. "},
{title:"Empty",id:"empty",enabled:"0",type:"textbox",vstring:{regex:"^[.:A-Za-z\\d\/]+$",required:"true"},tooltip:"URL to forward users to if a query fails. If not defined the value for ERROR is used."},
{title:"Error",id:"error",enabled:"0",type:"textbox",vstring:{regex:"^[.:A-Za-z\\d\/]+$",required:"true"},tooltip:"URL to forward users to if an error occurs. Ugly old MapServer error messages will appear if this is not defined"},
{title:"Template",id:"template",enabled:"0",type:"textbox",vstring:{regex:"^[.:A-Za-z\\d\/]+$",required:"true"},tooltip:"Template file or URL to use in presenting the results to the user in an interactive mode"},
{title:"MaxTemplate",id:"maxtemplate",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"\/\+]*$",required:"true"},tooltip:"Template to be used if below the minimum scale for the app "},
{title:"MinTemplate",id:"mintemplate",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Template to be used if above the maximum scale for the app"},
{title:"Footer",id:"footer",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use AFTER anything else is sent. Multiresult query modes only."},
{title:"Header",id:"*header",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use BEFORE everything else has been sent. Multiresult query modes only."},
{title:"TempPath",id:"temppath",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Path for storing temporary files. "},
{title:"MaxScale",id:"maxscale",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The minimum scale at which this interface is valid."},
{title:"MinScale",id:"minscale",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The maximum scale at which this interface is valid."}];


var LEGENDPROPERTIES = [{title:"Status",id:"status",enabled:"0",type:"dropdown",doptions:"on|off|embed"},
{title:"KeySize",id:"keysize",enabled:"0",type:"label"},{title:"X",id:"$KEYSIZE&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size of symbol key boxes in pixels."},
{title:"Y",id:"$KEYSIZE&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size of symbol key boxes in pixels."},
{title:"ImageColor",id:"imagecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to initialize the legend with (i.e. the background)."},
{title:"OutlineColour",id:"outlinecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for outlining symbol key boxes."},
{title:"KeySpacing",id:"keyspacing",enabled:"0",type:"label"},
{title:"X",id:"$KEYSPACING&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Spacing between symbol key boxes ([y]) and labels ([x]) in pixels."},
{title:"Y",id:"$KEYSPACING&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Spacing between symbol key boxes ([y]) and labels ([x]) in pixels."},
{title:"Position",id:"position",enabled:"0",type:"dropdown",doptions:"ul|uc|ur|ll|lc|lr"},{title:"PostLabelCache",id:"postlabelcache",enabled:"0",type:"switch",doptions:"True|False"},
{title:"Template",id:"template",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"\/\+]*$",required:"true"},tooltip:"HTML legend template file."},
{title:"Transparent",id:"transparent",enabled:"0",type:"switch"},{title:"Interlace",id:"interlace",enabled:"0",type:"switch",doptions:"True|False"}];

var SCALEBARPROPERTIES = [{title:"Status",id:"status",enabled:"0",type:"dropdown",doptions:"on|off|embed"},
{title:"Size",id:"size",enabled:"0",type:"label"},{title:"X",id:"$SIZE&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size in pixels of the scalebar. Labeling is not taken into account."},
{title:"Y",id:"$SIZE&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size in pixels of the scalebar. Labeling is not taken into account."},
{title:"BackgroundColor",id:"backgroundcolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for scalebar background, not the image background."},
{title:"Color",id:"color",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for drawing all features if attribute tables are not used."},
{title:"ImageColor",id:"imagecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to initialize the scalebar with (i.e. background)."},
{title:"Outlinecolor",id:"outlinecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for outlining individual intervals."},
{title:"Units",id:"units",enabled:"0",type:"dropdown",doptions:"dd|feet|inches|kilometers|meters|miles|nauticalmiles|percentages|pixels"},
{title:"Intervals",id:"intervals",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Number of intervals to break the scalebar into. "},
{title:"Position",id:"position",enabled:"0",type:"dropdown",doptions:"ul|uc|ur|ll|lc|lr"},
{title:"PostLabelCache",id:"postlabelcache",enabled:"0",type:"switch",doptions:"True|False"},
{title:"Align",id:"align",enabled:"0",type:"dropdown",doptions:"left|center|right"},
{title:"Style",id:"style",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Chooses the scalebar style. Valid styles are 0 and 1."},
{title:"Interlace",id:"interlace",enabled:"0",type:"radio",doptions:"true|false"},
{title:"Transparent",id:"transparent",enabled:"0",type:"switch"}];


var QUERYMAPPROPERIES = [{title:"Status",id:"status",enabled:"0",type:"switch"},{title:"Style",id:"style",enabled:"0",type:"dropdown",doptions:"normal|hilite|selected"},
{title:"Color",id:"color",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color in which features are highlighted."},
{title:"Size",id:"size",enabled:"0",type:"label"},
{title:"X",id:"$SIZE&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size of the map in pixels."},
{title:"Y",id:"$SIZE&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size of the map in pixels."}];


var OUTPUTFORMATPROPERTIES = [{title:"Name",id:"name",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"The name to use in the IMAGETYPE keyword of the map file to select this output format."},
{title:"Driver",id:"driver",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"The name of the driver to use to generate this output format."},
{title:"MIMEType",id:"mimetype",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Provide the mime type to be used when returning results over the web."},
{title:"ImageMode",id:"imagemode",enabled:"0",type:"dropdown",doptions:"PC256|RGB|RGBA|INT16|FLOAT32|FEATURE"},
{title:"Extension",id:"extension",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Provide the extension to use when creating files of this type. "},
{title:"FormatOption",id:"formatoption",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Provides a driver or format specific option. Zero or more FORMATOPTION statement may be present within a OUTPUTFORMAT declaration."},
{title:"Transparent",id:"transparent",enabled:"0",type:"switch"}];


var REFERENCEPROPERTIES = [{title:"Status",id:"status",enabled:"0",type:"switch"},
{title:"Image",id:"image",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"\/\+]*$",required:"true"},tooltip:"Full filename of the base reference image. Must be a GIF image."},
{title:"Extent",id:"extent",enabled:"0",type:"label"},
{title:"Minx",id:"$EXTENT&minx",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the base reference image."},
{title:"Miny",id:"$EXTENT&miny",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the base reference image."},
{title:"Maxx",id:"$EXTENT&maxx",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the base reference image."},
{title:"Maxy",id:"$EXTENT&maxy",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The spatial extent of the base reference image."},
{title:"Size",id:"size",enabled:"0",type:"label"},{title:"X",id:"$SIZE&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size, in pixels, of the base reference image."},
{title:"Y",id:"$SIZE&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size, in pixels, of the base reference image."},
{title:"Color",id:"color",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color in which the reference box is drawn."},
{title:"OutlineColor",id:"outlinecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for outlining the reference box. Set any component to -1 for no outline."},
{title:"Marker",id:"marker",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Defines a symbol (from the symbol file) to use when the box becomes too small "},
{title:"MarkerSize",id:"markersize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Defines the size of the symbol to use instead of a box "},
{title:"MinBoxSize",id:"minboxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"If box is smaller than MINBOXSIZE (use box width or height) then use the symbol defined by MARKER and MARKERSIZE."},
{title:"MaxBoxSize",id:"maxboxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"If box is greater than MAXBOXSIZE (use box width or height) then draw nothing"}];


var CLASSPROPERTIES = [{title:"Status",id:"status",enabled:"0",type:"switch"},
{title:"Name",id:"name",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Name to use in legends for this class. If not set class won’t show up in legend."},
{title:"Group",id:"group",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Allows for grouping of classes. "},
{title:"Expression",id:"expression",enabled:"0",type:"textbox",vstring:{required:"true"},tooltip:"Four types of expressions are now supported to define which class a feature belongs to: String comparisons, regular expressions, logical expressions, and string functions"},
{title:"MaxScaleDenom",id:"maxscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum scale at which this CLASS is drawn."},
{title:"MinScaleDenom",id:"minscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum scale at which this CLASS is drawn. "},
{title:"Text",id:"text",enabled:"0",type:"textbox",vstring:{required:"true"},tooltip:"Text to label features in this class with."},
{title:"Validation",id:"validation",enabled:"0",type:"textbox",vstring:{required:"true"},tooltip:""},
{title:"KeyImage",id:"keyimage",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Full filename of the legend image for the CLASS. This image is used when building a legend"},
{title:"Template",id:"template",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template file or URL to use in presenting query results to the user."},
{title:"Symbol",id:"symbol",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:""},
{title:"Size",id:"size",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Size, in pixels."},
{title:"MinSize",id:"minsize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:""},
{title:"MaxSize",id:"maxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:""},
{title:"Color",id:"color",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:""},
{title:"OutlineColor",id:"outlinecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:""},
{title:"BackgroundColor",id:"backgroundcolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:""},
{title:"Debug",id:"debug",enabled:"0",type:"switch"}];


	var LABELPROPERTIES = [{title:"MaxScaleDenom",id:"maxscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum scale at which this LABEL is drawn."},
{title:"MinScaleDenom",id:"minscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum scale at which this LABEL is drawn."},
{title:"Expression",id:"expression",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Expression that determines when the LABEL is to be applied."},
{title:"Text",id:"text",enabled:"0",type:"textbox",vstring:{required:"true"},tooltip:"Text to label features with (useful when multiple labels are used). Overrides values obtained from the LAYER LABELITEM and the CLASS TEXT."},
{title:"Color",id:"color",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to draw text with."},
{title:"OutlineColor",id:"outlinecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to draw a one pixel outline around the characters in the text."},
{title:"OutlineWidth",id:"outlinewidth",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Width of the outline if OUTLINECOLOR has been set. "},
{title:"Angle",id:"angle",enabled:"0",type:"dropdown",doptions:"double|auto|auto2|follow|attribute"},
{title:"Type",id:"type",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Type of font to use. Generally bitmap fonts are faster to draw then TrueType fonts. "},
{title:"Font",id:"font",enabled:"0",type:"textbox"},
{title:"Size",id:"size",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Text size. Use a number to give the size in pixels of your TrueType font based label, or any of the other 5 listed keywords for bitmap fonts."},
{title:"AntiAlias",id:"antialias",enabled:"0",type:"radio",doptions:"TRUE|FALSE"},
{title:"Buffer",id:"buffer",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Padding, in pixels, around labels. Useful for maintaining spacing around text to enhance readability. Available only for cached labels."},
{title:"Position",id:"position",enabled:"0",type:"dropdown",doptions:"ul|uc|ur|cl|cc|cr|ll|lc|lr|auto"},
{title:"Force",id:"force",enabled:"0",type:"radio",doptions:"TRUE|FALSE"},
{title:"Partials",id:"partials",enabled:"0",type:"radio",doptions:"TRUE|FALSE"},
{title:"MinDistance",id:"mindistance",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Minimum distance between duplicate labels."},
{title:"MaxLength",id:"maxlength",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"This keyword interacts with the WRAP keyword so that line breaks only occur after the defined number of characters."},
{title:"Wrap",id:"wrap",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Character that represents an end-of-line condition in label text, thus resulting in a multi-line label. Interacts with MAXLENGTH for conditional line wrapping after a given number of characters"},
{title:"Align",id:"align",enabled:"0",type:"dropdown",doptions:"left|center|right"},
{title:"MaxOverlapAngle",id:"maxoverlapangle",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Angle threshold to use in filtering out ANGLE FOLLOW labels in which characters overlap"},
{title:"MaxSize",id:"maxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum font size to use when scaling text (pixels). "},
{title:"MinSize",id:"minsize",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum font size to use when scaling text (pixels). "},
{title:"MinFeatureSize",id:"minfeaturesize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Minimum size a feature must be to be labeled. Given in pixels."},
{title:"OffSet",id:"offset",enabled:"0",type:"label"},
{title:"X",id:"$OFFSET&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Offset values for labels, relative to the lower left hand corner of the label and the label point. Given in pixels."},
{title:"Y",id:"$OFFSET&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Offset values for labels, relative to the lower left hand corner of the label and the label point. Given in pixels."},
{title:"Priority",id:"priority",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"The priority parameter takes an integer value between 1 (lowest) and 10 (highest)."},
{title:"Repeatdistance",id:"repeatdistance",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"The label will be repeated on every line of a multiline shape and will be repeated multiple times along a given line at an interval of REPEATDISTANCE pixels."},
{title:"ShadowColor",id:"shadowcolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color of drop shadow. A label with the same text will be rendered in this color before the main label is drawn, resulting in a shadow effect on the the label characters."},
{title:"ShadowSize",id:"shadowsize",enabled:"0",type:"label"},
{title:"X",id:"$SHADOWSIZE&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Shadow offset in pixels, see SHADOWCOLOR."},
{title:"Y",id:"$SHADOWSIZE&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Shadow offset in pixels, see SHADOWCOLOR."},
{title:"Encoding",id:"encoding",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Supported encoding format to be used for labels. If the format is not supported, the label will not be drawn."}];


	var STYLEPROPERTIES = [{title:"Symbol",id:"symbol",enabled:"0",type:"textbox",vstring:{regex:"^[.:A-Za-z\\d\/]+$",required:"true"},tooltip:""},
{title:"Size",id:"size",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Height, in layer SIZEUNITS, of the symbol/pattern to be used."},
{title:"Width",id:"width",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"WIDTH refers to the thickness of line work drawn, in layer SIZEUNITS."},
{title:"Color",id:"color",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for drawing features."},
{title:"Angle",id:"angle",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Angle, given in degrees, to rotate the symbol (counter clockwise). "},
{title:"AngleItem",id:"angleitem",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:""},
{title:"AntiAlias",id:"antialias",enabled:"0",type:"dropdown",doptions:"TRUE|FALSE"},
{title:"Gap",id:"gap",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"GAP specifies the distance between SYMBOLs (center to center) for decorated lines and polygon fills in layer SIZEUNITS. For polygon fills, GAP specifies the distance between SYMBOLs in both the X and the Y direction. For lines, the centers of the SYMBOLs are placed on the line. "},
{title:"GeomTransform",id:"geomtransform",enabled:"0",type:"dropdown",doptions:"bbox|centroid|end|labelpnt|labelpoly|start|vertices|<expression>"},
{title:"InitialGap",id:"initialgap",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Used to indicate that the current feature will be transformed before the actual style is applied. "},
{title:"LineCap",id:"linecap",enabled:"0",type:"dropdown",doptions:"butt|round|square"},
{title:"LineJoin",id:"linejoin",enabled:"0",type:"dropdown",doptions:"round|miter|bevel"},
{title:"LineJoinMaxSize",id:"linejoinmaxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Sets the max length of the miter LINEJOIN type. The value represents a coefficient which multiplies a current symbol size."},
{title:"MaxScaleDenom",id:"maxscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum scale at which this STYLE is drawn. "},
{title:"MinScaleDenom",id:"minscaledenom",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum scale at which this STYLE is drawn."},
{title:"MaxSize",id:"maxsize",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum size in pixels to draw a symbol. "},
{title:"MinSize",id:"minsize",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum size in pixels to draw a symbol. "},
{title:"MaxWidth",id:"maxwidth",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Maximum width in pixels to draw the line work."},
{title:"MinWidth",id:"minwidth",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Minimum width in pixels to draw the line work."},
{title:"OffSet",id:"offset",enabled:"0",type:"label"},
{title:"X",id:"$OFFSET&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Geometry offset values in layer SIZEUNITS. In the general case, SIZEUNITS will be pixels."},
{title:"Y",id:"$OFFSET&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Geometry offset values in layer SIZEUNITS. In the general case, SIZEUNITS will be pixels."},
{title:"Opacity",id:"opacity",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:""},
{title:"OutlineColor",id:"outlinecolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for outlining polygons and certain marker symbols (ellipse, vector polygons and truetype). Has no effect for lines."},
{title:"OutlineWidth",id:"outlinewidth",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Width in pixels for the outline. "},
{title:"PolarOffset",id:"polaroffset",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Offset given in polar coordinates."},
{title:"BackgroundColor",id:"backgroundcolor",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Color to use for non-transparent symbols."}];

       
	var CLUSTERPROPERTIES = [{title:"MaxDistance",id:"maxdistance",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Specifies the distance of the search region (rectangle or ellipse) in pixel positions."},
{title:"Region",id:"region",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Defines the search region around a feature in which the neighbouring features are negotiated. Can be ‘rectangle’ or ‘ellipse’."},
{title:"Group",id:"group",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"This expression evaluates to a string and only the features that have the same group value are negotiated."},
{title:"Filter",id:"filter",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"We can define the FILTER expression filter some of the features from the final output. This expression evaluates to a boolean value and if this value is false the corresponding shape is filtered out. "},
{title:"Buffer",id:"buffer",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"Defines a buffer region around the map extent in pixels."}];


	var COMPSITEPROPERTIES = [{title:"Opacity",id:"opacity",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Sets the opacity level (or the inability to see through the layer) of all classed pixels for a given layer. A value of 100 is opaque and 0 is fully transparent."},
{title:"ComPop",id:"compop",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z-\\d\\s]+$",required:"true"},tooltip:"Name of the compositing operator to use when blending the temporary image onto the main map image. "}];


       var GRIDPROPERTIES = [{title:"MinArcs",id:"minarcs",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The minimum number of arcs to draw. Increase this parameter to get more lines. "},
{title:"MaxArcs",id:"maxarcs",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The maximum number of arcs to draw. Decrease this parameter to get fewer lines. "},
{title:"MinInterval",id:"mininterval",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The minimum number of intervals to try to use. The distance between the grid lines, in the units of the grid’s coordinate system."},
{title:"MaxInterval",id:"maxinterval",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The maximum number of intervals to try to use. The distance between the grid lines, in the units of the grid’s coordinate system."},
{title:"MinSubdivide",id:"minsubdivide",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The minimum number of segments to use when rendering an arc. If the lines should be very curved, use this to smooth the lines by adding more segments. "},
{title:"MaxSubDivide",id:"maxsubdivide",enabled:"0",type:"textbox",vstring:{regex:"^\\-?\\d*\\.?\\d*$",required:"true"},tooltip:"The maximum number of segments to use when rendering an arc. If the graticule should be very straight, use this to minimize the number of  for faster rendering. "},
{title:"LabelFormat",id:"labelformat",enabled:"0",type:"dropdown",doptions:"DD|DDMM|DDMMSS|C format string"},
{title:"C format string",id:"cformatstring",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:""}];



       var JOINPROPERTIES = [{title:"Connection",id:"connection",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Database connection string to retrieve remote data."},
{title:"ConnectionType",id:"connectiontype",enabled:"0",type:"dropdown",doptions:"csv|mysql|postgresql"},
{title:"Footer",id:"footer",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use after a layer’s set of results have been sent. In other words, this header HTML will be displayed after the contents of the TEMPLATE HTML."},
{title:"From",id:"from",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Join column in the dataset. This is case sensitive."},
{title:"Header",id:"*header",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use before a layer’s set of results have been sent. In other words, this header HTML will be displayed before the contents of the TEMPLATE HTML."},
{title:"Name",id:"name",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Unique name for this join. "},
{title:"Table",id:"table",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"For file-based joins this is the name of XBase or comma delimited file (relative to the location of the mapfile) to join TO. For PostgreSQL support this is the name of the PostgreSQL table to join TO."},
{title:"Template",id:"template",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Template to use with one-to-many joins. The template is processed once for each record and can only contain substitutions for columns in the joined table."},
{title:"To",id:"to",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Join column in the table to be joined. This is case sensitive."},
{title:"Type",id:"type",enabled:"0",type:"dropdown",doptions:"ONE-TO-ONE|ONE-TO-MANY"}];



       var LEADERPROPERTIES = [{title:"GridStep",id:"gridstep",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Specifies the number of pixels between positions that are tested for a label line. "},
       {title:"MaxDistance",id:"maxdistance",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Specifies the maximum distance in pixels from the normal label location that a leader line can be drawn."}];



       var SYMBOLPROPERTIES = [{title:"AnchorPoint",id:"anchorpoint",enabled:"0",type:"label"},
{title:"X",id:"$ANCHORPOINT&x",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Used to specify the location (within the symbol) that is to be used as an anchorpoint when rotating the symbol and placing the symbol on a map."},
{title:"Y",id:"$ANCHORPOINT&y",enabled:"0",type:"textbox",vstring:{regex:"^\\d+$",required:"true"},tooltip:"Used to specify the location (within the symbol) that is to be used as an anchorpoint when rotating the symbol and placing the symbol on a map."},
{title:"AntiAlias",id:"antialias",enabled:"0",type:"dropdown",doptions:"TRUE|FALSE"},
{title:"Character",id:"character",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Character used to reference a particular TrueType font character. You’ll need to figure out the mapping from the keyboard character to font character."},
{title:"Filled",id:"filled",enabled:"0",type:"dropdown",doptions:"TRUE|FALSE"},
{title:"Font",id:"font",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Name of TrueType font to use as defined in the FONTSET."},
{title:"Image",id:"image",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Image (GIF or PNG) to use as a marker or brush for type pixmap symbols."},
{title:"Name",id:"name",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Alias for the symbol. To be used in CLASS STYLE objects."},
{title:"Points",id:"points",enabled:"0",type:"textbox",vstring:{regex:"^[\\d ]*$",required:"true",onblurfuc:"SPACESPLITEVEN"},tooltip:"Signifies the start of a sequence of points that make up a symbol of TYPE vector or that define the x and y radius of a symbol of TYPE ellipse. "},
{title:"Transparent",id:"transparent",enabled:"0",type:"colorpicker",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"Sets a transparent color for the input image for pixmap symbols, or determines whether all shade symbols should have a transparent background. "},
{title:"Type",id:"type",enabled:"0",type:"dropdown",doptions:"ellipse|hatch|pixmap|svg|truetype|vector"}];

var FEATUREPROPERTIES = [{title:"Points",id:"points",enabled:"0",type:"textbox",vstring:{regex:"^[\\d ]*$",required:"true",onblurfuc:"SPACESPLITEVEN"},tooltip:"A set of xy pairs terminated with an END."},
{title:"Items",id:"items",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"Comma separated list of the feature attributes"},
{title:"Text",id:"text",enabled:"0",type:"textbox",vstring:{regex:"^[A-Za-z\\d\\s]+$",required:"true"},tooltip:"String to use for labeling this feature."},
{title:"Wkt",id:"wkt",enabled:"0",type:"textbox",vstring:{regex:"^[^\'\"]*$",required:"true"},tooltip:"A geometry expressed in OpenGIS Well Known Text geometry format. This feature is only supported if MapServer is built with OGR or GEOS support."}];


 /*Default Values */

 var DEFAULTVAL={Map:{"angle":"0","CONFIG^cgi_context_url":"","CONFIG^ms_encryption_key":"","CONFIG^ms_errorfile":"",
"CONFIG^ms_nonsquare":"","CONFIG^on_missing_data":"","CONFIG^proj_lib":"","datapattern":"","debug":"",defresolution:"72",
"$EXTENT&minx":"","$EXTENT&miny":"","$EXTENT&maxx":"","$EXTENT&maxy":"","fontset":"",
"imagecolor":"#FFFFFF","imagequality":"80","imagetype":"png","interlace":"","maxsize":"","name":"","resolution":"72","scaledenom":"",
"shapepath":"","$SIZE&x":"","$SIZE&y":"","status":"","symbolset":"","templatepattern":"","transparent":"","units":""},
Layer:{"classgroup":"","classitem":"","connection":"","connectiontype":"",
"data":"","debug":"","dump":"","encoding":"","$EXTENT&minx":"","$EXTENT&miny":"","$EXTENT&maxx":"","$EXTENT&maxy":"",
"filter":"","filteritem":"","footer":"","geomtransform":"","group":"","header":"","labelangleitem":"","labelcache":"on",
"labelitem":"","labelmaxscaledenom":"","labelminscaledenom":"","labelrequires":"","labelsizeitem":"","mask":"","maxfeatures":"",
"maxgeowidth":"","maxscaledenom":"","mingeowidth":"","minscaledenom":"","name":"","offsite":"","opacity":"",
"plugin":"","postlabelcache":"false","processing":"","requires":"","sizeunits":"",
"status":"","styleitem":"","symbolscaledenom":"","template":"","tileindex":"","tileitem":"",
"tilesrs":"","":"","toleranceunits":"","transparency":"","transform":"true","type":"","units":"","utfdata":"","utfitem":""},
Web:{"browseformat":"","empty":"","error":"","footer":"","header":"","imagepath":"","imageurl":"",
"legendformat":"image/svg+xml","LOG":"","maxscaledenom":"25000","maxscale":"100000","maxtemplate":"",
"minscaledenom":"3000","minscale":"","mintemplate":"","queryformat":"text/html","template":"","temppath":""},
Outputformat:{"driver":"","extension":"png","formatoption":"GAMMA=0.75","imagemode":"rgb","mimetype":"image/png",
"name":"png","transparent":"on"},
Legend:{"imagecolor":"#FFFFFF","interlace":"on","$KEYSIZE&x":"20","$KEYSIZE&y":"10","$KEYSPACING&x":"5","$KEYSPACING&y":"5","outlinecolor":"#FFFFFF",
"position":"lr","postlabelcache":"false","status":"","template":"","transparent":"off"},
Scalebar:{"align":"Center","backgroundcolor":"#FFFFFF","color":"#FFFFFF","imagecolor":"#FFFFFF","interlace":"on","intervals":"4","outlinecolor":"#FFFFFF","position":"lr",
"postlabelcache":"false","$SIZE&x":"","$SIZE&y":"","status":"off","style":"","transparent":"off","units":"miles"},
Querymap:{"color":"#FFFF00","$SIZE&x":"","$SIZE&y":"","status":"","Style":""},
Reference:{"color":"#FF0000","$EXTENT&minx":"","$EXTENT&miny":"","$EXTENT&maxx":"","$EXTENT&maxy":"",
"image":"","marker":"","markersize":"","minboxsize":"","maxboxsize":"","outlinecolor":"#FFFFFF","$SIZE&x":"","$SIZE&y":"","status":"off"},
Class:{"debug":"","expression":"","group":"","keyimage":"","maxscaledenom":"",
"maxsize":"","minscaledenom":"","minsize":"","name":""},
Label:{"align":"","angle":"0","antialias":"FALSE","backgroundcolor":"#FFFFFF","backgroundshadowcolor":"#FFFFFF","$BACKGROUNDSHADOWSIZE&x":"1",
"$BACKGROUNDSHADOWSIZE&y":"1","buffer":"0","color":"#FFFFFF","encoding":"","expression":"","font":"","force":"FALSE","maxlength":"",
"maxoverlapangle":"","maxscaledenom":"","maxsize":"256","mindistance":"","minfeaturesize":"","minscaledenom":"",
"minsize":"4","$OFFSET&x":"","$OFFSET&y":"","outlinecolor":"#FFFFFF","outlinewidth":"","partials":"true","position":"","priority":"1",
"repeatdistance":"","shadowcolor":"","$SHADOWSIZE&x":"","$SHADOWSIZE&y":"","size":"","text":"","type":"","wrap":""},
Class:{"backgroundcolor":"#FFFFFF","color":"#FFFFFF","debug":"","expression":"",
"group":"","keyimage":"","maxscaledenom":"","maxsize":"","minscaledenom":"","minsize":"","name":"",
"outlinecolor":"#FFFFFF","size":"","status":"","symbol":"","template":"","text":""},
Style:{"angle":"0","angleitem":"","antialias":"","backgroundcolor":"","color":"#FFFFFF","gap":"",
"geomtransform":"","initialgap":"","linecap":"","linejoin":"","linejoinmaxsize":"3","maxscaledenom":"","maxsize":"500","maxwidth":"32",
"minscaledenom":"","minsize":"0","minwidth":"0","$OFFSET&x":"","$OFFSET&y":"","opacity":"","outlinecolor":"#FFFFFF","outlinewidth":"0",
"pattern":"","polaroffset":"","size":"","symbol":"","width":"1.0"},
Cluster:{"maxdistance":"","region":"","buffer":"0","group":"","filter":""},
Composite:{"opacity":"","compop":""},
Grid:{"labelformat":"","minarcs":"","maxarcs":"","mininterval":"","maxinterval":"","minsubdivide":"","maxsubdivide":"256"},
Join:{"connection":"","connectiontype":"","footer":"","from":"","header":"","name":"","table":"","template":"","to":"0","type":"one-to-one"},
Leader:{"gridstep":"","maxdistance":""},
Symbol:{"$ANCHORPOINT&x":"0.5","$ANCHORPOINT&y":"0.5","antialias":"false","character":"","filled":"false","font":"","image":"",
"name":"","points":"","transparent":"","type":""},Feature:{"points":"","items":"","text":"","wkt":""},
Projection:{"proj4":""}};
